#!/bin/bash
# Yarn -> Mojang (Official) mapping remapper for Minecraft 1.20.1

SRC_ROOT="src"
FILES=$(find "$SRC_ROOT" -name "*.java" -type f 2>/dev/null)
COUNT=$(echo "$FILES" | wc -l)
echo "Remapping $COUNT Java files..."

remap() { sed -i "s|${1}|${2}|g" $FILES 2>/dev/null; true; }

echo "Phase 1: Import paths..."

# CLIENT RENDER MODEL JSON
remap 'net\.minecraft\.client\.render\.model\.json\.JsonUnbakedModel' 'net.minecraft.client.renderer.block.model.BlockModel'
# CLIENT RENDER MODEL
remap 'net\.minecraft\.client\.render\.model\.BakedModel' 'net.minecraft.client.resources.model.BakedModel'
remap 'net\.minecraft\.client\.render\.model\.BakedQuad' 'net.minecraft.client.renderer.block.model.BakedQuad'
remap 'net\.minecraft\.client\.render\.model\.BakedQuadFactory' 'net.minecraft.client.renderer.block.model.FaceBakery'
remap 'net\.minecraft\.client\.render\.model\.ModelLoader' 'net.minecraft.client.resources.model.ModelBakery'
remap 'net\.minecraft\.client\.render\.model\.MultipartBakedModel' 'net.minecraft.client.resources.model.MultiPartBakedModel'
remap 'net\.minecraft\.client\.render\.model\.WeightedBakedModel' 'net.minecraft.client.resources.model.WeightedBakedModel'
# CLIENT RENDER BLOCK ENTITY
remap 'net\.minecraft\.client\.render\.block\.entity\.BlockEntityRenderDispatcher' 'net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher'
remap 'net\.minecraft\.client\.render\.block\.entity\.BlockEntityRenderer' 'net.minecraft.client.renderer.blockentity.BlockEntityRenderer'
# CLIENT RENDER BLOCK
remap 'net\.minecraft\.client\.render\.block\.BlockModelRenderer' 'net.minecraft.client.renderer.block.ModelBlockRenderer'
remap 'net\.minecraft\.client\.render\.block\.BlockModels' 'net.minecraft.client.renderer.block.BlockModelShaper'
# CLIENT RENDER CHUNK
remap 'net\.minecraft\.client\.render\.chunk\.ChunkBuilder' 'net.minecraft.client.renderer.chunk.ChunkRenderDispatcher'
remap 'net\.minecraft\.client\.render\.chunk\.ChunkOcclusionDataBuilder' 'net.minecraft.client.renderer.chunk.VisGraph'
remap 'net\.minecraft\.client\.render\.chunk\.ChunkOcclusionData' 'net.minecraft.client.renderer.chunk.VisibilitySet'
# CLIENT RENDER ENTITY
remap 'net\.minecraft\.client\.render\.entity\.EntityRenderDispatcher' 'net.minecraft.client.renderer.entity.EntityRenderDispatcher'
remap 'net\.minecraft\.client\.render\.entity\.EntityRenderer' 'net.minecraft.client.renderer.entity.EntityRenderer'
remap 'net\.minecraft\.client\.render\.item\.ItemRenderer' 'net.minecraft.client.renderer.entity.ItemRenderer'
# CLIENT RENDER CORE
remap 'net\.minecraft\.client\.render\.BackgroundRenderer' 'net.minecraft.client.renderer.FogRenderer'
remap 'net\.minecraft\.client\.render\.BufferBuilderStorage' 'net.minecraft.client.renderer.RenderBuffers'
remap 'net\.minecraft\.client\.render\.BufferBuilder' 'com.mojang.blaze3d.vertex.BufferBuilder'
remap 'net\.minecraft\.client\.render\.BufferRenderer' 'com.mojang.blaze3d.vertex.BufferUploader'
remap 'net\.minecraft\.client\.render\.Camera' 'net.minecraft.client.Camera'
remap 'net\.minecraft\.client\.render\.CameraSubmersionType' 'net.minecraft.client.renderer.FogRenderer.FogMode'
remap 'net\.minecraft\.client\.render\.Frustum' 'net.minecraft.client.renderer.culling.Frustum'
remap 'net\.minecraft\.client\.render\.GameRenderer' 'net.minecraft.client.renderer.GameRenderer'
remap 'net\.minecraft\.client\.render\.LightmapTextureManager' 'net.minecraft.client.renderer.LightTexture'
remap 'net\.minecraft\.client\.render\.OverlayTexture' 'net.minecraft.client.renderer.texture.OverlayTexture'
remap 'net\.minecraft\.client\.render\.RenderLayers' 'net.minecraft.client.renderer.ItemBlockRenderTypes'
remap 'net\.minecraft\.client\.render\.RenderLayer' 'net.minecraft.client.renderer.RenderType'
remap 'net\.minecraft\.client\.render\.VertexConsumerProvider' 'net.minecraft.client.renderer.MultiBufferSource'
remap 'net\.minecraft\.client\.render\.VertexConsumer' 'com.mojang.blaze3d.vertex.VertexConsumer'
remap 'net\.minecraft\.client\.render\.VertexFormats' 'com.mojang.blaze3d.vertex.DefaultVertexFormat'
remap 'net\.minecraft\.client\.render\.VertexFormat' 'com.mojang.blaze3d.vertex.VertexFormat'
remap 'net\.minecraft\.client\.render\.WorldRenderer' 'net.minecraft.client.renderer.LevelRenderer'
remap 'net\.minecraft\.client\.render\.\*' 'net.minecraft.client.renderer.*'
# CLIENT COLOR
remap 'net\.minecraft\.client\.color\.block\.BlockColorProvider' 'net.minecraft.client.color.block.BlockColor'
remap 'net\.minecraft\.client\.color\.item\.ItemColorProvider' 'net.minecraft.client.color.item.ItemColor'
remap 'net\.minecraft\.client\.color\.world\.BiomeColors' 'net.minecraft.client.renderer.BiomeColors'
remap 'net\.minecraft\.client\.color\.world\.FoliageColors' 'net.minecraft.world.level.FoliageColor'
remap 'net\.minecraft\.client\.color\.world\.GrassColors' 'net.minecraft.world.level.GrassColor'
# CLIENT FONT
remap 'net\.minecraft\.client\.font\.GlyphRenderer' 'net.minecraft.client.gui.font.glyphs.BakedGlyph'
remap 'net\.minecraft\.client\.font\.TextHandler' 'net.minecraft.client.StringSplitter'
remap 'net\.minecraft\.client\.font\.TextRenderer' 'net.minecraft.client.gui.Font'
# CLIENT GL
remap 'net\.minecraft\.client\.gl\.Framebuffer' 'com.mojang.blaze3d.pipeline.RenderTarget'
remap 'net\.minecraft\.client\.gl\.GlUniform' 'com.mojang.blaze3d.shaders.Uniform'
remap 'net\.minecraft\.client\.gl\.ShaderProgram' 'net.minecraft.client.renderer.ShaderInstance'
remap 'net\.minecraft\.client\.gl\.VertexBuffer' 'com.mojang.blaze3d.vertex.VertexBuffer'
remap 'net\.minecraft\.client\.gl\.WindowFramebuffer' 'com.mojang.blaze3d.pipeline.MainTarget'
# CLIENT GUI
remap 'net\.minecraft\.client\.gui\.hud\.DebugHud' 'net.minecraft.client.gui.components.DebugScreenOverlay'
remap 'net\.minecraft\.client\.gui\.hud\.InGameHud' 'net.minecraft.client.gui.Gui'
remap 'net\.minecraft\.client\.gui\.navigation\.GuiNavigationPath' 'net.minecraft.client.gui.ComponentPath'
remap 'net\.minecraft\.client\.gui\.navigation\.GuiNavigation' 'net.minecraft.client.gui.navigation.FocusNavigationEvent'
remap 'net\.minecraft\.client\.gui\.screen\.narration\.NarrationMessageBuilder' 'net.minecraft.client.gui.narration.NarrationElementOutput'
remap 'net\.minecraft\.client\.gui\.screen\.narration\.NarrationPart' 'net.minecraft.client.gui.narration.NarratedElementType'
remap 'net\.minecraft\.client\.gui\.screen\.DownloadingTerrainScreen' 'net.minecraft.client.gui.screens.ReceivingLevelScreen'
remap 'net\.minecraft\.client\.gui\.screen\.LevelLoadingScreen' 'net.minecraft.client.gui.screens.LevelLoadingScreen'
remap 'net\.minecraft\.client\.gui\.screen\.option\.OptionsScreen' 'net.minecraft.client.gui.screens.OptionsScreen'
remap 'net\.minecraft\.client\.gui\.screen\.option\.VideoOptionsScreen' 'net.minecraft.client.gui.screens.VideoSettingsScreen'
remap 'net\.minecraft\.client\.gui\.screen\.Screen' 'net.minecraft.client.gui.screens.Screen'
remap 'net\.minecraft\.client\.gui\.widget\.ButtonWidget' 'net.minecraft.client.gui.components.Button'
remap 'net\.minecraft\.client\.gui\.DrawContext' 'net.minecraft.client.gui.GuiGraphics'
remap 'net\.minecraft\.client\.gui\.Drawable' 'net.minecraft.client.gui.components.Renderable'
remap 'net\.minecraft\.client\.gui\.Element' 'net.minecraft.client.gui.components.events.GuiEventListener'
remap 'net\.minecraft\.client\.gui\.ScreenRect' 'net.minecraft.client.gui.navigation.ScreenRectangle'
remap 'net\.minecraft\.client\.gui\.Selectable' 'net.minecraft.client.gui.narration.NarratableEntry'
# CLIENT INPUT
remap 'net\.minecraft\.client\.input\.KeyCodes' 'com.mojang.blaze3d.platform.InputConstants'
# CLIENT MODEL
remap 'net\.minecraft\.client\.model\.ModelPart' 'net.minecraft.client.model.geom.ModelPart'
# CLIENT NETWORK
remap 'net\.minecraft\.client\.network\.ClientPlayNetworkHandler' 'net.minecraft.client.multiplayer.ClientPacketListener'
remap 'net\.minecraft\.client\.network\.ClientPlayerEntity' 'net.minecraft.client.player.LocalPlayer'
# CLIENT OPTION
remap 'net\.minecraft\.client\.option\.CloudRenderMode' 'net.minecraft.client.CloudStatus'
remap 'net\.minecraft\.client\.option\.GameOptions' 'net.minecraft.client.Options'
remap 'net\.minecraft\.client\.option\.GraphicsMode' 'net.minecraft.client.GraphicsStatus'
remap 'net\.minecraft\.client\.option\.SimpleOption' 'net.minecraft.client.OptionInstance'
remap 'net\.minecraft\.client\.option\.\*' 'net.minecraft.client.*'
# CLIENT PARTICLE
remap 'net\.minecraft\.client\.particle\.BillboardParticle' 'net.minecraft.client.particle.SingleQuadParticle'
remap 'net\.minecraft\.client\.particle\.SpriteBillboardParticle' 'net.minecraft.client.particle.TextureSheetParticle'
# CLIENT SOUND
remap 'net\.minecraft\.client\.sound\.PositionedSoundInstance' 'net.minecraft.client.resources.sounds.SimpleSoundInstance'
# CLIENT TEXTURE
remap 'net\.minecraft\.client\.texture\.NativeImageBackedTexture' 'net.minecraft.client.renderer.texture.DynamicTexture'
remap 'net\.minecraft\.client\.texture\.NativeImage' 'com.mojang.blaze3d.platform.NativeImage'
remap 'net\.minecraft\.client\.texture\.PlayerSkinTexture' 'net.minecraft.client.renderer.texture.HttpTexture'
remap 'net\.minecraft\.client\.texture\.SpriteAtlasTexture' 'net.minecraft.client.renderer.texture.TextureAtlas'
remap 'net\.minecraft\.client\.texture\.SpriteContents' 'net.minecraft.client.renderer.texture.SpriteContents'
remap 'net\.minecraft\.client\.texture\.Sprite' 'net.minecraft.client.renderer.texture.TextureAtlasSprite'
remap 'net\.minecraft\.client\.texture\.TextureManager' 'net.minecraft.client.renderer.texture.TextureManager'
remap 'net\.minecraft\.client\.texture\.AbstractTexture' 'net.minecraft.client.renderer.texture.AbstractTexture'
remap 'net\.minecraft\.client\.texture\.MipmapHelper' 'net.minecraft.client.renderer.texture.MipmapGenerator'
# CLIENT UTIL
remap 'net\.minecraft\.client\.util\.InputUtil' 'com.mojang.blaze3d.platform.InputConstants'
remap 'net\.minecraft\.client\.util\.Window' 'com.mojang.blaze3d.platform.Window'
remap 'net\.minecraft\.client\.util\.math\.MatrixStack' 'com.mojang.blaze3d.vertex.PoseStack'
remap 'net\.minecraft\.client\.util\.math\.Rect2i' 'net.minecraft.client.renderer.Rect2i'
# CLIENT WORLD
remap 'net\.minecraft\.client\.world\.ClientChunkManager' 'net.minecraft.client.multiplayer.ClientChunkCache'
remap 'net\.minecraft\.client\.world\.ClientWorld' 'net.minecraft.client.multiplayer.ClientLevel'
# CLIENT CORE
remap 'net\.minecraft\.client\.MinecraftClient' 'net.minecraft.client.Minecraft'
remap 'net\.minecraft\.client\.RunArgs' 'net.minecraft.client.main.GameConfig'
# BLOCK
remap 'net\.minecraft\.block\.entity\.BlockEntity' 'net.minecraft.world.level.block.entity.BlockEntity'
remap 'net\.minecraft\.block\.BlockRenderType' 'net.minecraft.world.level.block.RenderShape'
remap 'net\.minecraft\.block\.BlockState' 'net.minecraft.world.level.block.state.BlockState'
remap 'net\.minecraft\.block\.Blocks' 'net.minecraft.world.level.block.Blocks'
remap 'net\.minecraft\.block\.SideShapeType' 'net.minecraft.world.level.block.SupportType'
remap 'net\.minecraft\.block\.Block' 'net.minecraft.world.level.block.Block'
remap 'net\.minecraft\.block\.\*' 'net.minecraft.world.level.block.*'
# ENTITY
remap 'net\.minecraft\.entity\.effect\.StatusEffectInstance' 'net.minecraft.world.effect.MobEffectInstance'
remap 'net\.minecraft\.entity\.effect\.StatusEffects' 'net.minecraft.world.effect.MobEffects'
remap 'net\.minecraft\.entity\.Entity' 'net.minecraft.world.entity.Entity'
# FLUID
remap 'net\.minecraft\.fluid\.FluidState' 'net.minecraft.world.level.material.FluidState'
remap 'net\.minecraft\.fluid\.Fluids' 'net.minecraft.world.level.material.Fluids'
remap 'net\.minecraft\.fluid\.Fluid' 'net.minecraft.world.level.material.Fluid'
# ITEM
remap 'net\.minecraft\.item\.ItemConvertible' 'net.minecraft.world.level.ItemLike'
remap 'net\.minecraft\.item\.ItemStack' 'net.minecraft.world.item.ItemStack'
# NBT
remap 'net\.minecraft\.nbt\.NbtCompound' 'net.minecraft.nbt.CompoundTag'
# NETWORK
remap 'net\.minecraft\.network\.packet\.s2c\.play\.ChunkData' 'net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData'
remap 'net\.minecraft\.network\.packet\.s2c\.play\.LightData' 'net.minecraft.network.protocol.game.ClientboundLightUpdatePacketData'
remap 'net\.minecraft\.network\.packet\.s2c\.play\.UnloadChunkS2CPacket' 'net.minecraft.network.protocol.game.ClientboundForgetLevelChunkPacket'
remap 'net\.minecraft\.network\.PacketByteBuf' 'net.minecraft.network.FriendlyByteBuf'
# REGISTRY
remap 'net\.minecraft\.registry\.entry\.RegistryEntry' 'net.minecraft.core.Holder'
remap 'net\.minecraft\.registry\.tag\.FluidTags' 'net.minecraft.tags.FluidTags'
remap 'net\.minecraft\.registry\.RegistryKeys' 'net.minecraft.core.registries.Registries'
remap 'net\.minecraft\.registry\.RegistryKey' 'net.minecraft.resources.ResourceKey'
remap 'net\.minecraft\.registry\.Registries' 'net.minecraft.core.registries.BuiltInRegistries'
# RESOURCE
remap 'net\.minecraft\.resource\.metadata\.ResourceMetadataSerializer' 'net.minecraft.server.packs.metadata.MetadataSectionSerializer'
remap 'net\.minecraft\.resource\.ReloadableResourceManagerImpl' 'net.minecraft.server.packs.resources.ReloadableResourceManager'
remap 'net\.minecraft\.resource\.ResourceFactory' 'net.minecraft.server.packs.resources.ResourceProvider'
remap 'net\.minecraft\.resource\.ResourceManager' 'net.minecraft.server.packs.resources.ResourceManager'
remap 'net\.minecraft\.resource\.ResourceReload' 'net.minecraft.server.packs.resources.ReloadInstance'
remap 'net\.minecraft\.resource\.Resource' 'net.minecraft.server.packs.resources.Resource'
remap 'net\.minecraft\.resource\.\*' 'net.minecraft.server.packs.resources.*'
# SOUND
remap 'net\.minecraft\.sound\.SoundEvents' 'net.minecraft.sounds.SoundEvents'
# TEXT
remap 'net\.minecraft\.text\.MutableText' 'net.minecraft.network.chat.MutableComponent'
remap 'net\.minecraft\.text\.OrderedText' 'net.minecraft.util.FormattedCharSequence'
remap 'net\.minecraft\.text\.StringVisitable' 'net.minecraft.network.chat.FormattedText'
remap 'net\.minecraft\.text\.Style' 'net.minecraft.network.chat.Style'
remap 'net\.minecraft\.text\.Text' 'net.minecraft.network.chat.Component'
# UTIL (specific first)
remap 'net\.minecraft\.util\.collection\.EmptyPaletteStorage' 'net.minecraft.util.ZeroBitStorage'
remap 'net\.minecraft\.util\.collection\.PackedIntegerArray' 'net.minecraft.util.SimpleBitStorage'
remap 'net\.minecraft\.util\.crash\.CrashException' 'net.minecraft.ReportedException'
remap 'net\.minecraft\.util\.crash\.CrashReportSection' 'net.minecraft.CrashReportCategory'
remap 'net\.minecraft\.util\.crash\.CrashReport' 'net.minecraft.CrashReport'
remap 'net\.minecraft\.util\.function\.BooleanBiFunction' 'net.minecraft.world.phys.shapes.BooleanOp'
remap 'net\.minecraft\.util\.hit\.BlockHitResult' 'net.minecraft.world.phys.BlockHitResult'
remap 'net\.minecraft\.util\.math\.random\.LocalRandom' 'net.minecraft.world.level.levelgen.SingleThreadedRandomSource'
remap 'net\.minecraft\.util\.math\.random\.Random' 'net.minecraft.util.RandomSource'
remap 'net\.minecraft\.util\.math\.BlockBox' 'net.minecraft.world.level.levelgen.structure.BoundingBox'
remap 'net\.minecraft\.util\.math\.BlockPos' 'net.minecraft.core.BlockPos'
remap 'net\.minecraft\.util\.math\.Box' 'net.minecraft.world.phys.AABB'
remap 'net\.minecraft\.util\.math\.ChunkPos' 'net.minecraft.world.level.ChunkPos'
remap 'net\.minecraft\.util\.math\.ChunkSectionPos' 'net.minecraft.core.SectionPos'
remap 'net\.minecraft\.util\.math\.ColorHelper' 'net.minecraft.util.FastColor'
remap 'net\.minecraft\.util\.math\.Direction' 'net.minecraft.core.Direction'
remap 'net\.minecraft\.util\.math\.MathHelper' 'net.minecraft.util.Mth'
remap 'net\.minecraft\.util\.math\.Vec3d' 'net.minecraft.world.phys.Vec3'
remap 'net\.minecraft\.util\.math\.\*' 'net.minecraft.core.*'
remap 'net\.minecraft\.util\.profiler\.Profiler' 'net.minecraft.util.profiling.ProfilerFiller'
remap 'net\.minecraft\.util\.shape\.VoxelShapes' 'net.minecraft.world.phys.shapes.Shapes'
remap 'net\.minecraft\.util\.shape\.VoxelShape' 'net.minecraft.world.phys.shapes.VoxelShape'
remap 'net\.minecraft\.util\.Formatting' 'net.minecraft.ChatFormatting'
remap 'net\.minecraft\.util\.Identifier' 'net.minecraft.resources.ResourceLocation'
remap 'net\.minecraft\.util\.Language' 'net.minecraft.locale.Language'
remap 'net\.minecraft\.util\.Util' 'net.minecraft.Util'
# WORLD
remap 'net\.minecraft\.world\.biome\.source\.BiomeCoords' 'net.minecraft.world.level.biome.BiomeResolver'
remap 'net\.minecraft\.world\.biome\.BiomeEffects' 'net.minecraft.world.level.biome.BiomeSpecialEffects'
remap 'net\.minecraft\.world\.biome\.BiomeKeys' 'net.minecraft.world.level.biome.Biomes'
remap 'net\.minecraft\.world\.biome\.Biome' 'net.minecraft.world.level.biome.Biome'
remap 'net\.minecraft\.world\.biome\.ColorResolver' 'net.minecraft.world.level.ColorResolver'
remap 'net\.minecraft\.world\.chunk\.light\.LightingProvider' 'net.minecraft.world.level.lighting.LevelLightEngine'
remap 'net\.minecraft\.world\.chunk\.ChunkNibbleArray' 'net.minecraft.world.level.chunk.DataLayer'
remap 'net\.minecraft\.world\.chunk\.ChunkSection' 'net.minecraft.world.level.chunk.LevelChunkSection'
remap 'net\.minecraft\.world\.chunk\.ChunkStatus' 'net.minecraft.world.level.chunk.ChunkStatus'
remap 'net\.minecraft\.world\.chunk\.PalettedContainer' 'net.minecraft.world.level.chunk.PalettedContainer'
remap 'net\.minecraft\.world\.chunk\.Palette' 'net.minecraft.world.level.chunk.Palette'
remap 'net\.minecraft\.world\.chunk\.ReadableContainer' 'net.minecraft.world.level.chunk.PalettedContainerRO'
remap 'net\.minecraft\.world\.chunk\.WorldChunk' 'net.minecraft.world.level.chunk.LevelChunk'
remap 'net\.minecraft\.world\.chunk\.Chunk' 'net.minecraft.world.level.chunk.ChunkAccess'
remap 'net\.minecraft\.world\.chunk\.\*' 'net.minecraft.world.level.chunk.*'
remap 'net\.minecraft\.world\.dimension\.DimensionType' 'net.minecraft.world.level.dimension.DimensionType'
remap 'net\.minecraft\.world\.gen\.chunk\.DebugChunkGenerator' 'net.minecraft.world.level.levelgen.DebugLevelSource'
remap 'net\.minecraft\.world\.BlockRenderView' 'net.minecraft.world.level.BlockAndTintGetter'
remap 'net\.minecraft\.world\.BlockView' 'net.minecraft.world.level.BlockGetter'
remap 'net\.minecraft\.world\.LightType' 'net.minecraft.world.level.LightLayer'
remap 'net\.minecraft\.world\.WorldView' 'net.minecraft.world.level.LevelReader'
remap 'net\.minecraft\.world\.World' 'net.minecraft.world.level.Level'

echo "Phase 2: Class name usage in code..."
remap 'MinecraftClient' 'Minecraft'
remap 'SideShapeType' 'SupportType'
remap 'BlockColorProvider' 'BlockColor'
remap 'ItemColorProvider' 'ItemColor'
remap 'FoliageColors' 'FoliageColor'
remap 'GrassColors' 'GrassColor'
remap 'TextRenderer' 'Font'
remap 'ShaderProgram' 'ShaderInstance'
remap 'DrawContext' 'GuiGraphics'
remap 'InGameHud' 'Gui'
remap 'ButtonWidget' 'Button'
remap 'BackgroundRenderer' 'FogRenderer'
remap 'BufferBuilderStorage' 'RenderBuffers'
remap 'LightmapTextureManager' 'LightTexture'
remap 'RenderLayers' 'ItemBlockRenderTypes'
remap 'RenderLayer' 'RenderType'
remap 'VertexConsumerProvider' 'MultiBufferSource'
remap 'VertexFormats' 'DefaultVertexFormat'
remap 'WorldRenderer' 'LevelRenderer'
remap 'BlockModelRenderer' 'ModelBlockRenderer'
remap 'SpriteAtlasTexture' 'TextureAtlas'
remap 'NativeImageBackedTexture' 'DynamicTexture'
remap 'MatrixStack' 'PoseStack'
remap 'ClientChunkManager' 'ClientChunkCache'
remap 'ClientWorld' 'ClientLevel'
remap 'ClientPlayNetworkHandler' 'ClientPacketListener'
remap 'ClientPlayerEntity' 'LocalPlayer'
remap 'CloudRenderMode' 'CloudStatus'
remap 'GameOptions' 'Options'
remap 'GraphicsMode' 'GraphicsStatus'
remap 'SimpleOption' 'OptionInstance'
remap 'SpriteBillboardParticle' 'TextureSheetParticle'
remap 'BillboardParticle' 'SingleQuadParticle'
remap 'StatusEffectInstance' 'MobEffectInstance'
remap 'StatusEffects' 'MobEffects'
remap 'ItemConvertible' 'ItemLike'
remap 'NbtCompound' 'CompoundTag'
remap 'PacketByteBuf' 'FriendlyByteBuf'
remap 'RegistryEntry' 'Holder'
remap 'MutableText' 'MutableComponent'
remap 'OrderedText' 'FormattedCharSequence'
remap 'Identifier' 'ResourceLocation'
remap 'Formatting' 'ChatFormatting'
remap 'MathHelper' 'Mth'
remap 'ChunkSectionPos' 'SectionPos'
remap 'BlockBox' 'BoundingBox'
remap 'Vec3d' 'Vec3'
remap 'VoxelShapes' 'Shapes'
remap 'BlockRenderView' 'BlockAndTintGetter'
remap 'BlockView' 'BlockGetter'
remap 'LightType' 'LightLayer'
remap 'WorldView' 'LevelReader'
remap 'ChunkNibbleArray' 'DataLayer'
remap 'WorldChunk' 'LevelChunk'
remap 'LightingProvider' 'LevelLightEngine'
remap 'BlockRenderType' 'RenderShape'

echo "Phase 3: Method renames..."
remap '\.getDefaultState()' '.defaultBlockState()'
remap '\.isOpaque()' '.canOcclude()'
remap '\.getCullingShape(' '.getOcclusionShape('
remap '\.isSideSolid(' '.isFaceSturdy('
remap '\.getOffsetX()' '.getStepX()'
remap '\.getOffsetY()' '.getStepY()'
remap '\.getOffsetZ()' '.getStepZ()'
remap '\.matchesType(' '.isSame('
remap '\.getFrameU(' '.getU('
remap '\.getFrameV(' '.getV('
remap '\.getMinU()' '.getU0()'
remap '\.getMinV()' '.getV0()'
remap '\.getMaxU()' '.getU1()'
remap '\.getMaxV()' '.getV1()'
remap '\.getVelocity(' '.getFlow('
remap '\.isIn(' '.is('
remap '\.getLightingProvider(' '.getLightEngine('
remap '\.getSectionArray()' '.getSections()'
remap '\.sectionCoordToIndex(' '.getSectionIndexFromSectionY('
remap '\.getBrightness(' '.getShade('
remap '\.getSession()' '.getUser()'
remap '\.getUuidOrNull()' '.getProfileId()'
remap '\.getBakedModelManager()' '.getModelManager()'
remap '\.getContents()' '.contents()'
remap 'Text\.translatable(' 'Component.translatable('
remap 'Text\.literal(' 'Component.literal('
remap '\.isAmbientOcclusionEnabled()' '.useAmbientOcclusion()'
remap '\.getMinX()' '.minX()'
remap '\.getMinY()' '.minY()'
remap '\.getMinZ()' '.minZ()'
remap '\.getMaxX()' '.maxX()'
remap '\.getMaxY()' '.maxY()'
remap '\.getMaxZ()' '.maxZ()'

echo "=== Remapping complete! ==="
